apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-healthcheck
  labels:
    app: fastapi-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-healthcheck
  template:
    metadata:
      labels:
        app: fastapi-healthcheck
    spec:
      containers:
        - name: fastapi-healthcheck
          image: asia-south1-docker.pkg.dev/project-6206f1cc-135e-44bd-acf/fastapi-images/gcp-fastapi-k-web:v2
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
